Sprint 13
esplusnin/ImageFeed pull request #8
Opened 2023-05-05 18:29 UTC by esplusnin

Покрытие тестами общее: 45,1%
ProfileViewController: 86,4%
ProfileViewPresenter: 73,5%
ImageListPresenter: 71,1%
ImageListController: 46,5%

2023-05-06 10:01 UTC, IBDesignable requested changes
Проделана огромная работа с тестами – очень круто! Этого не получилось бы достичь, если бы не рефакторинг на архитектурные модули в приложении. Очень круто получилось. 

Есть места с ошибками:
- в Service слой протекли UI-элементы
- в Presenter тоже не должны проникать элементы UIKit
- в слое View встречается обращение к сервисам, стораджам, осталась часть бизнес-логики. 
- dateformatter создаются на каждую потребность поработать с датами (у фотографий получается на каждую единицу будет создаваться по одному форматтеру)
- есть ссылочный цикл, который следует исправить. 

:) к твоему счастью(или не счастью?) раз уж кода написано много, придется исправлять эти ошибки везде в этом спринте, чтобы сдать работу. 
Будет отличная практика для работы с MVP и пригодится в следующем модуле тоже.

2023-05-06 10:01 UTC, IBDesignable requested changes
Проделана огромная работа с тестами – очень круто! Этого не получилось бы достичь, если бы не рефакторинг на архитектурные модули в приложении. Очень круто получилось. 

Есть места с ошибками:
- в Service слой протекли UI-элементы
- в Presenter тоже не должны проникать элементы UIKit
- в слое View встречается обращение к сервисам, стораджам, осталась часть бизнес-логики. 
- dateformatter создаются на каждую потребность поработать с датами (у фотографий получается на каждую единицу будет создаваться по одному форматтеру)
- есть ссылочный цикл, который следует исправить. 

:) к твоему счастью(или не счастью?) раз уж кода написано много, придется исправлять эти ошибки везде в этом спринте, чтобы сдать работу. 
Будет отличная практика для работы с MVP и пригодится в следующем модуле тоже.

2023-05-07 07:56 UTC, esplusnin commented on ImageFeed/Services/Protocols/ImageListServiceProtocol.swift
> +protocol ImagesListServiceProtocol: AnyObject{
Александра, очень рад вас снова видеть!)
Глупая ошибка, просто не внимательность, спасибо)

2023-05-07 09:49 UTC, esplusnin commented on ImageFeed/ViewControllers/ImagesList/ImageListViewController.swift
> +    var heightsOfRows: [String:CGFloat] = [:]
У меня, в том числе, в тестах завязан этот контейнер на проверку - подтягивает ли он из хэш таблицы высоту ячейки, если есть совпадающий айди.

2023-05-08 19:26 UTC, IBDesignable approved these changes

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/Services/DateService.swift
> +        return string
Настраивать форматтер точно так же как и создавать лучше раз за цикл работы. 

Либо делать это в инициализаторе DateService, либо использовать lazy var инициализацию свойства.

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/Services/DateService.swift
> +    let isoDateFormatter = ISO8601DateFormatter()
не забыть сделать приватными

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/Services/DateService.swift
> +        return date
в данном случае можно еще короче
```suggestion
        return isoDateFormatter.date(from: string)
```

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/ViewControllers/Auth/WebView/WebViewViewController.swift
> +        webView.progressView.isHidden = true
Есть два подхода, один – когда вьюшки очень тупые и лишь предоставляют доступ к своим подвьюшкам, тогда уместно по цепочке получать доступ и настраивать поведение подвью, 
второй – когда любой класс-вью реализованный программистом, закрывает приватным доступом все свои подвью и дает доступ через функции к ним. 

Авторы учебника в этом проекте настаивают на первом варианте, потому что проект очень прост. В промышленной разработке же такое редко встречается, потому что никто не хочет, чтобы из внешнего кода был неограниченный доступ. 

Попробуй в следующем проекте второй подход – будет полезно проектировать интерфейс доступа

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/ViewControllers/ImagesList/ImageListView.swift
> +    }
это не очень хорошо, потому что ничего вообще не гарантирует. Лучше написать так, тогда на уровне компиляции ты не сможешь этот метод использовать, если вьюконтроллер(другая сущность) не будет удовлетворять протоколам.

Кроме того, так ты можешь вообще передать два разных класса, которые будут выполнять разные задачи – в целом, так чаще в продакшене и бывает
```suggestion
    func setTableViewDelegateAndDataSource(delegate: UITableViewDelegate, dataSource: UITableViewDataSource) {
        tableView.delegate = viewController
        tableView.dataSource = viewController
    }
```

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/ViewControllers/ImagesList/ImageListViewController.swift
> +    var heightsOfRows: [String: CGFloat] = [:]
точно не надо приватными сделать?

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/ViewControllers/ImagesList/ImageListViewController.swift
> +                    }
Здесь можно лучше, чтобы не повторяться
```suggestion

                    UIBlockingProgressHUD.dismiss()
                    switch result {
                    case .success(let imageResult):
                        viewController.rescaleAndCenterImageInScrollView(image: imageResult.image)
                    case .failure:
                        self.alertPresenter?.presentErrorAlert()
                    }
```

2023-05-08 19:26 UTC, IBDesignable commented on ImageFeed/ViewControllers/Profile/ProfileViewController.swift
> +        profileView.accountDescription.text = presenter?.profile?.bio
у презентера можно реализовать в протоколе свойства fullName(String), username(string), bio(string) – опциональные или нет, на твой выбор. тогда такой цепочти можно избежать:
```
guard let presener else { return }
profileView.accountFullNameLabel.text = prestenet.fullName```

2023-05-18 08:43 UTC, merged